const SET_REMINDER = 'SET_REMINDER';

const SET_DATE_REMINDER = 'ADD_DATE_REMINDER';

const SET_MONTH = 'UI/SET_MONTH';

const DASHBOARD = {
  LOADING: 'DASHBOARD_LOADING',
  FETCH_SUCCESS: 'DASHBOARD_FETCH_SUCCESS',
  FETCH_FAILED: 'DASHBOARD_FETCH_FAILED',
  RESET_DATA: 'DASHBOARD_RESET_DATA',
  SET_DATA: 'DASHBOARD_SET_DATA'
};

const REMINDER = {
  NEW_REMINDER: 'UI/NEW_REMINDER',
  EDIT_REMINDER: 'UI/EDIT_REMINDER',
  SUBMIT_REMINDER: 'UI/SUBMIT_REMINDER',
  OPEN_REMINDER: 'UI/OPEN_REMINDER',
  CLOSE_REMINDER: 'UI/CLOSE_REMINDER'
}

export { 
  DASHBOARD, 
  SET_REMINDER, 
  SET_DATE_REMINDER, 
  SET_MONTH,
  REMINDER
};
